version: "3"
services:
  db:
    image: postgres:latest
    container_name: database-1-proyecto
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: docker
      POSTGRES_DB: database
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d
      - ./*.sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"
