services:
  db:
    image: postgres:latest
    container_name: database-1-proyecto-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./schemas.sql:/sql-files/schemas.sql
      - ./tables.sql:/sql-files/tables.sql
    ports:
      - "5433:5432"
